import type { DadWrappedContent } from "../types";

export const dadWrapped: DadWrappedContent = {
  dadName: "Dad",
  year: 2026,
  openingMessage: "A year of legendary dad behavior, carefully measured by the people who know you best.",
  cards: [
    {
      id: "opening",
      type: "intro",
      eyebrow: "Your year in review",
      title: "DAD WRAPPED",
      caption: "The numbers are unofficial. The legend is not.",
      image: "/img/cover.jpg",
      theme: "orange",
    },
    {
      id: "mvp",
      type: "photo",
      eyebrow: "The family's most valuable person",
      title: "ONE DAD. COUNTLESS SAVES.",
      caption: "Always on call. Rarely impressed. Somehow prepared for everything.",
      images: ["/img/montage-1.jpg", "/img/montage-2.jpg", "/img/montage-3.jpg"],
      theme: "blue",
    },
    {
      id: "problems",
      type: "stat",
      eyebrow: "Problems solved",
      title: "INCLUDING SEVERAL NOBODY ASKED HIM TO SOLVE",
      value: 12847,
      caption: "Personal best. Again.",
      image: "/img/habit.jpg",
      theme: "lime",
    },
    {
      id: "kilometres",
      type: "stat",
      eyebrow: "Driven for the family",
      title: "THE LONG WAY, BECAUSE IT HAS LESS TRAFFIC",
      value: 24306,
      suffix: " KM",
      caption: "Pickups, drop-offs, errands, and one suspiciously efficient shortcut.",
      image: "/img/driving.jpg",
      theme: "yellow",
    },
    {
      id: "chai",
      type: "stat",
      eyebrow: "Cups of chai supervised",
      title: "EXPERT QUALITY CONTROL",
      value: 8942,
      caption: "Not too sweet. Not too cold. Exactly right.",
      image: "/img/habit.jpg",
      theme: "navy",
    },
    {
      id: "advice",
      type: "stat",
      eyebrow: "Advice sessions delivered",
      title: "FREE. UNLIMITED. SURPRISINGLY ACCURATE.",
      value: 3651,
      caption: "Acceptance rate: eventually 100%.",
      image: "/img/quote.jpg",
      theme: "orange",
    },
    {
      id: "phrase",
      type: "quote",
      eyebrow: "Your most-played phrase",
      title: "DAD'S TOP TRACK",
      quote: "Did you switch off the lights?",
      caption: "Played 2,409 times. Still charting.",
      theme: "blue",
    },
    {
      id: "support",
      type: "stat",
      eyebrow: "Family support score",
      title: "MATHEMATICALLY IMPOSSIBLE. VERY DAD.",
      value: 147,
      suffix: "%",
      caption: "For showing up before anyone even had to ask.",
      image: "/img/family.jpg",
      theme: "lime",
    },
    {
      id: "top-role",
      type: "photo",
      eyebrow: "Your number one role",
      title: "DAD",
      caption: "No contest. No close second.",
      image: "/img/family.jpg",
      theme: "yellow",
    },
    {
      id: "summary",
      type: "summary",
      eyebrow: "That's a wrap",
      title: "BUT THE BEST THINGS CAN'T BE COUNTED.",
      caption: "There are a few things we saved among the stars.",
      theme: "navy",
    },
  ],
  memories: [
    { id: "memory-1", position: { x: 16, y: 30 }, title: "The first adventure", memory: "Replace this with a short memory about a journey, a first, or a day you still talk about.", image: "/img/memory-1.jpg", alt: "A family memory with Dad" },
    { id: "memory-2", position: { x: 31, y: 18 }, title: "The lesson that stayed", memory: "Write about something he taught you without realizing how much it would matter later.", image: "/img/memory-2.jpg", alt: "Dad sharing a meaningful moment" },
    { id: "memory-3", position: { x: 44, y: 39 }, title: "A very Dad solution", memory: "Remember a moment when his unusual solution worked better than anyone expected.", image: "/img/memory-3.jpg", alt: "Dad solving a family problem" },
    { id: "memory-4", position: { x: 61, y: 25 }, title: "The laugh we remember", memory: "Add the story behind an inside joke or a moment when nobody could stop laughing.", image: "/img/memory-4.jpg", alt: "Dad laughing with family" },
    { id: "memory-5", position: { x: 79, y: 34 }, title: "Always there", memory: "Describe one of the quiet ways he has consistently shown up for the family.", image: "/img/memory-5.jpg", alt: "A quiet family moment with Dad" },
    { id: "memory-6", position: { x: 70, y: 58 }, title: "Our favorite ordinary day", memory: "Not every treasured memory is a milestone. Add one ordinary day that felt like home.", image: "/img/memory-6.jpg", alt: "An ordinary day spent with Dad" },
    { id: "memory-7", position: { x: 49, y: 68 }, title: "The family tradition", memory: "Write about a ritual, meal, holiday, or habit that would not feel the same without him.", image: "/img/memory-7.jpg", alt: "A family tradition with Dad" },
    { id: "memory-8", position: { x: 27, y: 60 }, title: "Still ahead of us", memory: "End with something you are looking forward to sharing with him in the years ahead.", image: "/img/memory-8.jpg", alt: "A hopeful memory with Dad" },
  ],
  closingMessage: "Every memory with you becomes part of who we are.",
};
